<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>ADEPR Admin | Admins</title>
<link rel="icon" type="image/png" href="../image/logo.png"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/css/admin.css"></head>
<body data-page="admins"><div class="admin-wrapper"><aside class="sidebar" id="sidebar"><a class="brand" href="dashboard.php"><img src="../image/logo.png" alt="logo"><span>ADEPR Admin</span></a><nav class="side-menu nav flex-column">
<a class="nav-link" data-page="dashboard" href="dashboard.php"><i class="fa-solid fa-chart-line"></i>Dashboard</a><a class="nav-link" data-page="images" href="images.php"><i class="fa-solid fa-image"></i>Images</a><a class="nav-link" data-page="videos" href="videos.php"><i class="fa-solid fa-video"></i>Videos</a><a class="nav-link" data-page="updates" href="updates.php"><i class="fa-solid fa-newspaper"></i>Updates</a><a class="nav-link" data-page="notifications" href="notifications.php"><i class="fa-solid fa-bell"></i>Notifications</a><a class="nav-link" data-page="admins" href="admins.php"><i class="fa-solid fa-users-gear"></i>Admins</a></nav></aside>
<main class="main-panel"><div class="topbar d-flex justify-content-between align-items-center"><button id="sidebarToggle" class="btn btn-outline-secondary d-lg-none"><i class="fa-solid fa-bars"></i></button><h1 class="h5 mb-0">Manage Admins</h1><button class="btn btn-gradient" data-bs-toggle="modal" data-bs-target="#newAdminModal"><i class="fa-solid fa-user-plus me-1"></i>New Admin</button></div>
<section class="content"><div class="card card-soft p-3"><div class="table-responsive"><table class="table table-modern align-middle mb-0"><thead><tr><th>Username</th><th>Role</th><th>Action</th></tr></thead><tbody id="adminTableBody"></tbody></table></div></div></section></main></div>
<div class="modal fade" id="newAdminModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content">
<div class="modal-header"><h5 class="modal-title">Create New Admin</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="mb-3 input-icon-group"><i class="fa-solid fa-user"></i><input id="adminUsername" class="form-control" placeholder="Username"></div><div class="mb-3 input-icon-group"><i class="fa-solid fa-lock"></i><input id="adminPassword" type="password" class="form-control" placeholder="Password"></div><div class="mb-2 input-icon-group"><i class="fa-solid fa-shield-halved"></i><select id="adminRole" class="form-select"><option value="">Select role</option><option>Super Admin</option><option>Media Manager</option><option>Content Editor</option></select></div><p id="adminFormMessage" class="small mt-2 mb-0"></p></div>
<div class="modal-footer"><button class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button id="createAdminBtn" class="btn btn-gradient">Create Admin</button></div>
</div></div></div>
<div class="toast-stack" id="toastStack"></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="assets/js/admin.js"></script></body></html>

