<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>ADEPR Admin | Messages</title>
<link rel="icon" type="image/png" href="../image/logo.png"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/css/admin.css"></head>
<body data-page="messages"><div class="admin-wrapper"><aside class="sidebar" id="sidebar"><a class="brand" href="dashboard.php"><img src="../image/logo.png" alt="logo"><span>ADEPR Admin</span></a><nav class="side-menu nav flex-column">
<a class="nav-link" data-page="dashboard" href="dashboard.php"><i class="fa-solid fa-chart-line"></i>Dashboard</a><a class="nav-link" data-page="images" href="images.php"><i class="fa-solid fa-image"></i>Images</a><a class="nav-link" data-page="videos" href="videos.php"><i class="fa-solid fa-video"></i>Videos</a><a class="nav-link" data-page="updates" href="updates.php"><i class="fa-solid fa-newspaper"></i>Updates</a><a class="nav-link" data-page="notifications" href="notifications.php"><i class="fa-solid fa-bell"></i>Notifications</a><a class="nav-link" data-page="admins" href="admins.php"><i class="fa-solid fa-users-gear"></i>Admins</a><a class="nav-link" data-page="messages" href="messages.php"><i class="fa-solid fa-envelope"></i>Messages</a></nav></aside>
<main class="main-panel"><div class="topbar d-flex justify-content-between align-items-center"><button id="sidebarToggle" class="btn btn-outline-secondary d-lg-none"><i class="fa-solid fa-bars"></i></button><h1 class="h5 mb-0">Contact Messages</h1><a class="btn btn-gradient" href="logout.php"><i class="fa-solid fa-right-from-bracket me-1"></i>Logout</a></div>
<section class="content"><div class="card card-soft p-3"><div class="table-responsive"><table class="table table-modern align-middle mb-0"><thead><tr><th>Name</th><th>Email</th><th>Message</th><th>Date</th></tr></thead><tbody id="messagesTableBody"></tbody></table></div></div></section></main></div>
<div class="toast-stack" id="toastStack"></div><script src="assets/js/admin.js"></script></body></html>
