<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>ADEPR Admin | Notifications</title>
<link rel="icon" type="image/png" href="../image/logo.png"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/css/admin.css"></head>
<body data-page="notifications"><div class="admin-wrapper"><aside class="sidebar" id="sidebar"><a class="brand" href="dashboard.php"><img src="../image/logo.png" alt="logo"><span>ADEPR Admin</span></a><nav class="side-menu nav flex-column">
<a class="nav-link" data-page="dashboard" href="dashboard.php"><i class="fa-solid fa-chart-line"></i>Dashboard</a><a class="nav-link" data-page="images" href="images.php"><i class="fa-solid fa-image"></i>Images</a><a class="nav-link" data-page="videos" href="videos.php"><i class="fa-solid fa-video"></i>Videos</a><a class="nav-link" data-page="updates" href="updates.php"><i class="fa-solid fa-newspaper"></i>Updates</a><a class="nav-link" data-page="notifications" href="notifications.php"><i class="fa-solid fa-bell"></i>Notifications</a><a class="nav-link" data-page="admins" href="admins.php"><i class="fa-solid fa-users-gear"></i>Admins</a></nav></aside>
<main class="main-panel"><div class="topbar d-flex justify-content-between align-items-center"><button id="sidebarToggle" class="btn btn-outline-secondary d-lg-none"><i class="fa-solid fa-bars"></i></button><h1 class="h5 mb-0">Manage Notifications</h1></div>
<section class="content"><div class="card card-soft p-3 mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h6 mb-1">Create Announcement</h2><p class="small text-muted mb-0">Publish notification content for the public feed.</p></div><button type="button" class="btn btn-sm btn-outline-secondary" id="clearNotificationFormBtn">Clear</button></div><div class="row g-3"><div class="col-md-4"><input id="notificationTitle" class="form-control" placeholder="Title"></div><div class="col-md-3"><input id="notificationDate" type="date" class="form-control" placeholder="Publish date"></div><div class="col-md-5 d-grid gap-2"><button id="saveNotificationBtn" class="btn btn-gradient">Save Notification</button><p id="notificationFormMessage" class="small text-muted mb-0">Only admins can publish or update notifications.</p></div><div class="col-12"><textarea id="notificationDescription" class="form-control" rows="3" placeholder="Announcement details"></textarea></div></div></div>
<div class="card card-soft p-3" id="notificationsListWrapper"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h6 mb-0">Notifications List</h2><p class="small text-muted mb-0">Admin controls appear only in this dashboard.</p></div><span class="badge bg-secondary"><?= count($notifications) ?> items</span></div><?php if (empty($notifications)): ?><div class="text-center py-4 text-muted">No notifications have been published yet.</div><?php else: ?><ul class="list-group list-group-flush" id="notificationsTable"><?php foreach ($notifications as $notice): ?><li class="list-group-item d-flex justify-content-between align-items-start gap-3" data-id="<?= htmlspecialchars((string) $notice['id'], ENT_QUOTES, 'UTF-8') ?>" data-title="<?= htmlspecialchars((string) $notice['title'], ENT_QUOTES, 'UTF-8') ?>" data-date="<?= htmlspecialchars((string) $notice['publish_date'], ENT_QUOTES, 'UTF-8') ?>" data-description="<?= htmlspecialchars((string) $notice['description'], ENT_QUOTES, 'UTF-8') ?>"><div><strong><?= htmlspecialchars((string) $notice['title'], ENT_QUOTES, 'UTF-8') ?></strong><br><small class="text-muted"><?= htmlspecialchars(date('F j, Y', strtotime((string) ($notice['publish_date'] ?: $notice['created_at']))), ENT_QUOTES, 'UTF-8') ?></small><p class="mb-0 mt-2"><?= nl2br(htmlspecialchars((string) $notice['description'], ENT_QUOTES, 'UTF-8')) ?></p></div><div class="d-flex flex-column gap-2"><button type="button" class="btn btn-sm btn-outline-primary notification-edit" data-id="<?= htmlspecialchars((string) $notice['id'], ENT_QUOTES, 'UTF-8') ?>">Edit</button><button type="button" class="btn btn-sm btn-outline-danger notification-delete" data-id="<?= htmlspecialchars((string) $notice['id'], ENT_QUOTES, 'UTF-8') ?>">Delete</button></div></li><?php endforeach; ?></ul><?php endif; ?></div>
</section></main></div><script src="assets/js/admin.js"></script></body></html>

