<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>ADEPR Admin | Videos</title>
<link rel="icon" type="image/png" href="../image/logo.png"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="assets/css/admin.css"></head>
<body data-page="videos"><div class="admin-wrapper"><aside class="sidebar" id="sidebar"><a class="brand" href="dashboard.php"><img src="../image/logo.png" alt="logo"><span>ADEPR Admin</span></a><nav class="side-menu nav flex-column">
<a class="nav-link" data-page="dashboard" href="dashboard.php"><i class="fa-solid fa-chart-line"></i>Dashboard</a><a class="nav-link" data-page="images" href="images.php"><i class="fa-solid fa-image"></i>Images</a><a class="nav-link" data-page="videos" href="videos.php"><i class="fa-solid fa-video"></i>Videos</a><a class="nav-link" data-page="updates" href="updates.php"><i class="fa-solid fa-newspaper"></i>Updates</a><a class="nav-link" data-page="notifications" href="notifications.php"><i class="fa-solid fa-bell"></i>Notifications</a><a class="nav-link" data-page="admins" href="admins.php"><i class="fa-solid fa-users-gear"></i>Admins</a></nav></aside>
<main class="main-panel"><div class="topbar d-flex justify-content-between align-items-center"><button id="sidebarToggle" class="btn btn-outline-secondary d-lg-none"><i class="fa-solid fa-bars"></i></button><h1 class="h5 mb-0">Manage Videos</h1><button class="btn btn-gradient" id="openVideoModalBtn"><i class="fa-solid fa-plus me-1"></i>Add Video</button></div>
<section class="content"><div class="card card-soft p-3 mb-4"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label small">Search</label><input id="videoSearch" class="form-control" placeholder="Search by title/category"></div><div class="col-md-4"><label class="form-label small">Sort</label><select id="videoSort" class="form-select"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="category">Category</option></select></div><div class="col-md-4"><label class="form-label small">Category</label><select id="videoCategoryFilter" class="form-select"><option value="All">All</option><option value="Featured">Featured</option><option value="Choir">Choir Videos</option><option value="Priest">Priest Videos</option><option value="Events">Events</option></select></div></div></div>
<div class="card card-soft p-3 mb-4" id="videoFormCard"><h2 class="h6">Add YouTube Video</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Title *</label><input id="videoTitle" class="form-control" placeholder="Video title"></div><div class="col-md-6"><label class="form-label">Category *</label><select id="videoCategory" class="form-select"><option value="">Choose category</option><option value="Featured">Featured</option><option value="Choir">Choir Videos</option><option value="Priest">Priest Videos</option><option value="Events">Events</option></select></div><div class="col-md-6"><label class="form-label">YouTube Link *</label><input id="videoLink" class="form-control" placeholder="https://youtube.com/watch?v=..."></div><div class="col-md-6"><label class="form-label">Description *</label><input id="videoDescription" class="form-control" placeholder="Short description"></div><div class="col-12"><button id="saveVideoBtn" class="btn btn-gradient">Save Video</button><p id="videoFormMessage" class="small mb-0 mt-2"></p></div></div></div>
<ul class="nav nav-pills mb-3" id="videoTabs"></ul><div id="videoCards" class="row g-3"></div>
</section></main></div><div class="toast-stack" id="toastStack"></div><script src="assets/js/admin.js"></script></body></html>

